config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trains do
    resources :vagons, shallow: true
    resources :tickets, shallow: true
  end

  resources :tickets, only: [:index]
  resource :search_ticket, only: [:new, :show, :edit, :create] do
    post '/', to: 'search_tickets#find'
  end

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :tickets
  end

  # resources :vagons
  get 'welcome/index'

  root 'search_tickets#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true
  has_many :railway_stations_routes, dependent: :destroy
  has_many :routes, through: :railway_stations_routes
  has_many :station_indexs, through: :railway_stations_routes

  has_many :trains, inverse_of: :current_station, foreign_key: 'current_station_id'

  scope :ordered_railway_stations, -> { joins(:railway_stations_routes).order('railway_stations_routes.station_index').uniq }

  def update_position(route, order)
    station_route = station_route(route)
    station_route.update(station_index: order) if station_route
  end

  def update_time(route, coming_time, department_time)
    staion_route = station_route(route)
    staion_route.update(coming_time: coming_time, department_time: department_time) if staion_route
  end

  def position_in(route)
    station_route(route).try(:station_index)
  end

  def coming_time(route)
    station_route(route).try(:coming_time)&.strftime('%Y-%m-%dT%H:%M:%S')
  end

  def department_time(route)
    station_route(route).try(:department_time)&.strftime('%Y-%m-%dT%H:%M:%S')
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end

end

app/controllers/admin/railway_stations_controller.rb
module Admin
  class RailwayStationsController < Admin::BaseController
    before_action :set_railway_station, only: %i[show edit update destroy update_position update_time]

    def index
      @railway_stations = RailwayStation.all
    end

    def show
    end

    def new
      @railway_station = RailwayStation.new
    end

    def edit
    end

    def create
      @railway_station = RailwayStation.new(railway_station_params)

      respond_to do |format|
        if @railway_station.save
          format.html { redirect_to admin_railway_station_url(@railway_station), notice: "Railway station was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @railway_station.update(railway_station_params)
          format.html { redirect_to admin_railway_station_url(@railway_station), notice: "Railway station was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def update_position
      @route = Route.find(params[:route_id])
      @railway_station.update_position(@route, params[:station_index])
      redirect_to [:admin, @route]
    end

    def update_time
      @route = Route.find(params[:route_id])
      @railway_station.update_time(@route, params[:coming_time], params[:department_time])
      redirect_to [:admin, @route]
    end

    def destroy
      @railway_station.destroy

      respond_to do |format|
        format.html { redirect_to admin_railway_stations_url, notice: "Railway station was successfully destroyed." }
      end
    end

    private

      def set_railway_station
        @railway_station = RailwayStation.find(params[:id])
      end

      def railway_station_params
        params.require(:railway_station).permit(:title)
      end
  end

end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[show edit update destroy update_position update_time]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:station_index])
    redirect_to @route
  end

  def update_time
    @route = Route.find(params[:route_id])
    @railway_station.update_time(@route, params[:coming_time], params[:department_time])
    redirect_to @route
  end

  def destroy
    @railway_station.destroy

    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: "Railway station was successfully destroyed." }
    end
  end

  private

    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<%= form_with(model: [:admin, @railway_station]) do |form| %>

  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit', action: @railway_station.new_record? ? 'Створити' : 'Змінити')%>
  </div>
<% end %>

app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to t('common.show'), [:admin, railway_station]%></td>
  <td><%= link_to t('common.edit'), edit_admin_railway_station_path(railway_station) %></td>
  <td><%= button_to t('.destroy'), [:admin, railway_station], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/railway_stations/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.show'), [:admin, @railway_station] %> |
<%= link_to t('common.back'), admin_railway_stations_path %>

app/views/admin/railway_stations/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('common.title2') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations%>
  </tbody>
</table>

<br>

<%= link_to t('.new_station'), new_admin_railway_station_path %>

app/views/admin/railway_stations/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.back'), admin_railway_stations_path%>

app/views/admin/railway_stations/show.html.erb
<p>
  <strong><%= t('common.title2')%></strong>
  <%= @railway_station.title %>
</p>

<%= link_to t('common.edit'), edit_admin_railway_station_path(@railway_station) %> |
<%= link_to t('common.back'), admin_railway_stations_path %>