config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trains do
    resources :vagons, shallow: true
    resources :tickets, shallow: true
  end

  resources :tickets, only: [:index]
  resource :search_ticket, only: [:new, :show, :edit, :create] do
    post '/', to: 'search_tickets#find'
  end

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :tickets
  end

  # resources :vagons
  get 'welcome/index'

  root 'search_tickets#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :name, presence: true
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes, dependent: :destroy

  validate :stations_count
  before_validation :set_name

  scope :with_station, -> (station) { Route.joins(:railway_stations).where('railway_stations.id = ?', station.id) }

  def self.searched_routes(start_station, end_station)
    Route.with_station(start_station) &
    Route.with_station(end_station)
  end

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, 'Route should contain at least 2 stations')
    end
  end
end

app/controllers/admin/routes_controller.rb
module Admin
  class RoutesController < Admin::BaseController
    before_action :set_route, only: [:show, :edit, :update, :destroy]

    def index
      @routes = Route.all
    end

    def show
    end

    def new
      @route = Route.new
    end

    def create
      @route = Route.new(route_params)

      if @route.save
        redirect_to [:admin, @route]
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @route.update(route_params)
        redirect_to [:admin, @route]
      else
        render :edit
      end
    end

    def destroy
      @route.destroy
      redirect_to admin_routes_path
    end

    private

    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:name, railway_station_ids: [])
    end

  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end

end

app/views/admin/routes/_form.html.erb
<%= form_with(model: [:admin, @route]) do |form| %>

  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_station_ids, "Список станций" %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1>Edit Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes list</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Show', [:admin, route] %></td>
        <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
        <td><%= button_to 'Destroy', [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<% if @route.trains.empty? %>
  <p>Route has no trains</p>
<% else %>
  <p>Trains on this route: </p>
  <ul>
    <% @route.trains.each do |t|  %>
      <li><%= t.number %></li>
    <% end %>
  </ul>
<% end %>

<% if @route.railway_stations.empty? %>
  <p>Route has no stations</p>
<% else %>
  <table>
    <thead>
      <tr>
        <td width = 100px>Station name</td>
        <td>Position</td>
      </tr>
    </thead>
    <tbody>
      <% @route.railway_stations.ordered_railway_stations.each do |s|  %>
        <tr>
          <td><%= s.title %></td>
          <td>
            <%= form_tag update_position_admin_railway_station_path(s), method: :patch do %>
              <%= number_field_tag :station_index, s.position_in(@route)%>
              <%= hidden_field_tag :route_id, @route.id%>
              <%= submit_tag "Change" %>
            <% end %>
          </td>
          <td>
            <%= form_tag update_time_admin_railway_station_path(s), method: :patch do %>
              <%= datetime_field_tag :coming_time, s.coming_time(@route)%>
              <%= hidden_field_tag :route_id, @route.id%>
              <%= datetime_field_tag :department_time, s.department_time(@route)%>
              <%= hidden_field_tag :route_id, @route.id%>
              <%= submit_tag "Change" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>