config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trains do
    resources :vagons, shallow: true
    resources :tickets, shallow: true
  end

  resources :tickets, only: [:index]
  resource :search_ticket, only: [:new, :show, :edit, :create] do
    post '/', to: 'search_tickets#find'
  end

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :tickets
  end

  # resources :vagons
  get 'welcome/index'

  root 'search_tickets#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord

  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true
  has_many :tickets
  has_many :vagons, -> (train) { order("order_v #{train.vagon_order ? 'ASC' : 'DESC'}") }

  def type_places(vagon_type, places_type)
    vagons.where(type: vagon_type).sum(places_type)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to train_url(@train), notice: "Train was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
    end
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :vagon_order)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="field">
      <%= form.label 'Vagon order last to first?' %>
      <%= form.select :vagon_order, [true, false] %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= button_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains%>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<% if @train.route.blank? %>
  <p>Train has no route, just goal</p>
<% else %>
  <p>Train route is <%=  @train.route.name %> </p>
<% end %>


<% @train.vagons.each do |vagon| %>
  <p><%= link_to "#{vagon.vagon_id}", vagon %></p>
<% end %>

<%= link_to 'Add vagon', new_train_vagon_path(@train) %>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>