config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trains do
    resources :vagons, shallow: true
    resources :tickets, shallow: true
  end

  resources :tickets, only: [:index]
  resource :search_ticket, only: [:new, :show, :edit, :create] do
    post '/', to: 'search_tickets#find'
  end

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :tickets
  end

  # resources :vagons
  get 'welcome/index'

  root 'search_tickets#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vagon.rb
class Vagon < ApplicationRecord

  TYPES = %w(CoupeVagon CvVagon EconomVagon SittingVagon Vagon)

  belongs_to :train
  # enum type: [:compartment, :reserved_seat]
  validates :vagon_id, uniqueness: { scope: :train_id }

  before_validation :set_order

  private

  def set_order
    self.order_v = (Vagon.where(train_id: self.train_id).pluck(:order_v).max || 0) + 1
  end


end

app/controllers/vagons_controller.rb
class VagonsController < ApplicationController
  before_action :set_train, only: %i[new create]

  def index
    @vagons = Vagon.all
  end

  def show
    @vagon = Vagon.find(params[:id])
  end

  def new
    @vagon = Vagon.new
  end

  def edit; end

  def create
    # @train = Train.find(params[:train_id])
    @vagon = @train.vagons.new(vagon_params)

    respond_to do |format|
      if @vagon.save
        format.html { redirect_to @train, notice: 'Vagon was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vagon.update(vagon_params)
        format.html { redirect_to vagon_url(@vagon), notice: 'Vagon was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vagon.destroy

    respond_to do |format|
      format.html { redirect_to vagons_url, notice: 'Vagon was successfully destroyed.' }
    end
  end

  private

  def set_vagon
    @vagon = Vagon.find(params[:id])
  end

  def set_train
    @train = Train.find(params[:train_id])
  end

  def vagon_params
    params.require(:vagon).permit(:vagon_id, :type, :places_up, :places_down, :sitting_places,
      :side_places_up, :side_places_down, :order_v)
  end
end

app/views/vagons/_form.html.erb
<%= form_for [@train, @vagon] do |form| %>

  <%= render 'common/errors', resource: @vagon %>

  <div class="field">
    <%= form.label :vagon_id %>
    <%= form.number_field :vagon_id %>
  </div>

  <div class="field">
     <%= form.label :type %><br>
     <%= a = form.select :type, Vagon::TYPES %>
   </div>



  <div class="field">
    <%= form.label :places_up %>
    <%= form.number_field :places_up %>
  </div>

  <div class="field">
    <%= form.label :places_down %>
    <%= form.number_field :places_down %>
  </div>

  <div class="field">
    <%= form.label :side_places_down %>
    <%= form.number_field :side_places_down %>
  </div>

  <div class="field">
    <%= form.label :side_places_up %>
    <%= form.number_field :side_places_up %>
  </div>

  <div class="field">
    <%= form.label :sitting_places %>
    <%= form.number_field :sitting_places %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vagons/edit.html.erb
<h1>Edit Vagon</h1>

<%= render 'form', vagon: @vagon %>

<%= link_to 'Back', vagons_path %>

app/views/vagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vagons list</h1>

<table>
  <thead>
    <tr>
      <th>Vagon Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vagons.each do |vagon| %>
      <tr>
        <td><%= vagon.vagon_id %></td>
        <td><%= link_to 'Show', vagon %></td>
        <td><%= link_to 'Edit', edit_vagon_path(vagon) %></td>
        <td><%= button_to 'Destroy', vagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vagon', new_vagon_path %>

app/views/vagons/new.html.erb
<h1>New Vagon</h1>

<%= render 'form', vagon: @vagon %>

<%# <%= link_to 'Back', vagons_path %> %>

app/views/vagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vagon Id:</strong>
  <%= @vagon.vagon_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vagon.type %>
</p>

<% if @vagon.type == 'SittingVagon'%>
  <p>Sitting places: <%= @vagon.sitting_places %></p>
<% else %>
  <p>Places down: <%= @vagon.places_down %></p>
  <% if @vagon.type != 'CvVagon'%>
    <p>Places up: <%= @vagon.places_up %></p>
    <% if @vagon.type == 'EconomyVagon' %>
      <p>Side down places: <%= @vagon.side_places_down %></p>
      <p>Side up places: <%= @vagon.side_places_up %></p>
    <% end %>
  <% end %>
<% end %>
<% %>


<%= link_to 'Back', @vagon.train %> |